server {
    listen 8080;
    server_name _;
    
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Para Astro/SPA: intenta cargar el archivo, si no existe, carga index.html (o 404)
        try_files $uri $uri/ /index.html =404;
    }
}